
CREATE TABLE IF NOT EXISTS ROOM
(
    ROOMNUMBER  INTEGER PRIMARY KEY,
    TYPE        VARCHAR(20),
    SLEEPS      INTEGER,
    PRICE       DOUBLE
);

CREATE TABLE IF NOT EXISTS FOOD
(
    TYPE        VARCHAR(20) PRIMARY KEY,
    PRICE       DOUBLE
);

CREATE TABLE IF NOT EXISTS ADDITIONALSERVICES
(
    TYPE        VARCHAR(20) PRIMARY KEY,
    PRICE       DOUBLE
);

CREATE TABLE IF NOT EXISTS USER
(
    USERNAME        VARCHAR(20) PRIMARY KEY,
    LASTNAME        VARCHAR(20),
    FIRSTNAME       VARCHAR(20),
    EMAIL           VARCHAR(20),
    PASSWORD        VARCHAR(100),
    ACTIVE          BIT,
    ACTIVATIONCODE  VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ROLE
(
    NAME    VARCHAR(20) PRIMARY KEY
);

INSERT IGNORE INTO ROLE VALUES ('USER');
INSERT IGNORE INTO ROLE VALUES ('ADMIN');

CREATE TABLE IF NOT EXISTS USER_ROLE
(
    USER VARCHAR(20),
    ROLE VARCHAR(20),
    CONSTRAINT `fk_user` FOREIGN KEY (USER) REFERENCES USER (`username`),
    CONSTRAINT `fk_role` FOREIGN KEY (ROLE) REFERENCES ROLE (`name`)
);

INSERT INTO USER_ROLE (USER, ROLE)  SELECT 'ADMIN', 'ADMIN' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM USER_ROLE WHERE USER = 'ADMIN' AND ROLE = 'ADMIN')
AND 'ADMIN' IN (SELECT USERNAME FROM USER WHERE USERNAME = 'ADMIN');

CREATE TABLE IF NOT EXISTS BOOKING
(
    NUMBER      LONG NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER        VARCHAR(20),
    ROOM        INTEGER,
    PERSONS     INTEGER,
    ARRIVAL     DATE,
    DEPARTURE   DATE,
    FOOD        VARCHAR(20),
    DAYS        INTEGER,
    SERVICES    VARCHAR(20),
    AMOUNT      DOUBLE,
    STATUS      VARCHAR(20),
    CONSTRAINT `fk_room` FOREIGN KEY (ROOM) REFERENCES ROOM (`roomNumber`),
    CONSTRAINT `fk_food` FOREIGN KEY (FOOD) REFERENCES FOOD (`type`),
    CONSTRAINT `fk_services` FOREIGN KEY (SERVICES) REFERENCES ADDITIONALSERVICES (`type`)
);

INSERT IGNORE INTO ROOM VALUES (11, 'Стандарт', 2, 50);
INSERT IGNORE INTO ROOM VALUES (12, 'Стандарт', 2, 50);
INSERT IGNORE INTO ROOM VALUES (13, 'Стандарт', 2, 50);
INSERT IGNORE INTO ROOM VALUES (14, 'Стандарт', 3, 75);
INSERT IGNORE INTO ROOM VALUES (15, 'Стандарт', 2, 50);
INSERT IGNORE INTO ROOM VALUES (16, 'Полулюкс', 2, 80);
INSERT IGNORE INTO ROOM VALUES (17, 'Полулюкс', 3, 100);
INSERT IGNORE INTO ROOM VALUES (18, 'Стандарт', 3, 75);

INSERT IGNORE INTO ROOM VALUES (21, 'Стандарт', 2, 50);
INSERT IGNORE INTO ROOM VALUES (22, 'Полулюкс', 2, 80);
INSERT IGNORE INTO ROOM VALUES (23, 'Полулюкс', 3, 100);
INSERT IGNORE INTO ROOM VALUES (24, 'Стандарт', 3, 75);
INSERT IGNORE INTO ROOM VALUES (25, 'Стандарт', 2, 50);
INSERT IGNORE INTO ROOM VALUES (26, 'Люкс', 2, 100);
INSERT IGNORE INTO ROOM VALUES (27, 'Люкс', 2, 100);
INSERT IGNORE INTO ROOM VALUES (28, 'Стандарт', 3, 75);

INSERT IGNORE INTO ROOM VALUES (31, 'Люкс', 3, 140);
INSERT IGNORE INTO ROOM VALUES (32, 'Люкс', 4, 180);
INSERT IGNORE INTO ROOM VALUES (33, 'Люкс', 4, 180);
INSERT IGNORE INTO ROOM VALUES (34, 'Люкс', 3, 140);
INSERT IGNORE INTO ROOM VALUES (35, 'Люкс', 4, 180);

INSERT IGNORE INTO ROOM VALUES (41, 'Cуперлюкс', 10, 700);

INSERT IGNORE INTO FOOD VALUES ('нет', 0);
INSERT IGNORE INTO FOOD VALUES ('завтрак', 7);
INSERT IGNORE INTO FOOD VALUES ('полупансион', 20);

INSERT IGNORE INTO ADDITIONALSERVICES VALUES ('нет', 0);
INSERT IGNORE INTO ADDITIONALSERVICES VALUES ('трансфер', 15);
INSERT IGNORE INTO ADDITIONALSERVICES VALUES ('стоянка', 12);

COMMIT;